ROLE_PERMISSIONS = {
    "admin": {
        "agencies.read",
        "agencies.write",
        "events.read",
        "events.write",
        "ingest.write",
        "audit.read",
        "rbac.read",
        "users.manage",
        "alerts.read",
        "alerts.write",
        "reports.read",
        "reports.write",
        "surveillance.read",
        "surveillance.write",
        "communications.read",
        "communications.write",
        "network.read",
        "network.write",
        "heatmap.read",
        "heatmap.write",
        "models.read",
        "models.write",
        "inference.read",
        "inference.write",
        "graph.read",
        "graph.write",
    },
    "analyst": {
        "agencies.read",
        "events.read",
        "rbac.read",
        "alerts.read",
        "alerts.write",
        "reports.read",
        "reports.write",
        "surveillance.read",
        "communications.read",
        "communications.write",
        "network.read",
        "network.write",
        "heatmap.read",
        "heatmap.write",
        "models.read",
        "inference.read",
        "inference.write",
        "graph.read",
    },
    "viewer": {
        "events.read",
        "rbac.read",
        "alerts.read",
        "reports.read",
        "surveillance.read",
        "communications.read",
        "network.read",
        "heatmap.read",
        "models.read",
        "inference.read",
        "graph.read",
    },
    "security_agent": {
        "events.read",
        "alerts.read",
        "reports.read",
        "reports.write",
        "heatmap.read",
        "graph.read",
    },
    "ingestor": {
        "ingest.write",
        "events.write",
    },
    "auditor": {
        "audit.read",
        "rbac.read",
    },
}


def role_has_permission(role: str, permission: str) -> bool:
    return permission in ROLE_PERMISSIONS.get(role, set())
